### ISSUE TITLE
Blank preview page in admin section while using SuluThemeBundle and malconfigured webspace.xml 

### ISSUE THREAD

**Issue by svenbartak** [sulu/SuluThemeBundle#15]
| Q | A
| --- | ---
| Bug? | possible
| New Feature? | no
| Sulu Version | 1.5.x and 1.6.x
| Browser Version | No relevance

#### Actual Behavior

If you use the SuluThemeBundle and you forget to configure **all** webspace.xml with the `<theme>tbd</theme>` tag, the preview component in the admin area will only show a blank page. 

#### Expected Behavior

Showing the preview of the page and use the default theme configured in the `app/config/config.yml` when forgot the theme tag.

#### Steps to Reproduce

Integrate the SuluThemeBundle using this article [http://docs.sulu.io/en/latest/book/themes.html](url) and create two webspace (e.g. a.xml and b.xml). Configure the webspace a.xml with theme tag and webspace b.xml without the theme tag.

Using the webspace b in the admin area will show a blank page in the preview.

#### Possible Solutions

Probably using the default theme configured in the `app/config/config.yml`

**Comment by alexander-schranz** [comment]
Looks like this was fixed in 3.0.1
