### ISSUE TITLE
Not working with PHP 8

### ISSUE THREAD

**Issue by martinlagler** [sulu/SuluThemeBundle#29]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Bundle Version | Specific version or SHA of a commit
| Sulu Version | Specific version or SHA of a commit
| Browser Version | Browser name and version

#### Actual Behavior

Does not work with PHP 8 because of requirement to ` "sylius/theme-bundle": "^2.1"` 

#### Possible Solutions

Update to ` "sylius/theme-bundle": "^2.2"`

**Comment by alexander-schranz** [comment]
The `^2.1` includes `^2.2` and so a `composer update` should update to `sylius/theme-bundle: 2.2` or higher if your other dependencies allows it.

See: https://semver.madewithlove.com/?package=sylius%2Ftheme-bundle&constraint=^2.1&stability=stable
