### ISSUE TITLE
Sulu 1.6 compatibility

### ISSUE THREAD

**Issue by ampaze** [sulu/SuluThemeBundle#7]
I updated my Project to use Sulu 1.6 but composer says

> - sulu/theme-bundle 1.2.1 requires sulu/sulu 1.5.*

Is this only a matter of updating composer.json or is the ThemeBundle incompatible with Sulu 1.6?

**Comment by alexander-schranz** [comment]
@ampaze you need to update the theme bundle to `1.3.0` by updating your composer json.

**Comment by ampaze** [comment]
Thanks. I could have sworn I looked at the releases and couldn't find a newer version. Sorry :sweat:

**Comment by ampaze** [comment]
Unfortunately same problem

>  sulu/theme-bundle 1.3.0 requires sulu/sulu 1.5.*

**Comment by alexander-schranz** [comment]
@ampaze ok thats not good. Thank you for reporting! we will fixed it and create a new release soon! Until there I think you can go on `1.3.0-RC1`

**Comment by ampaze** [comment]
Was this forgotten?

**Comment by alexander-schranz** [comment]
@ampaze thx this issue is fixed with `1.3.1`
